name: rbp
channels:
  - conda-forge
  - pytorch
  - pyg
  - anaconda
dependencies:
  - python=3.7
  - conda-forge::setuptools=59.5.0
  - conda-forge::pip
  - pytorch::pytorch=1.10.*
  - pyg::pyg=2.0.4
  - anaconda::cython
  - pip:
      - biopython==1.79
      - click==8.0.4
      - forgi==2.1.2
      - pytorch-lightning==1.7.7
      - pandas==1.3.5
      - wandb==0.13.5